### ISSUE TITLE
a  issue from cargo xtask qemu （PANIC: called Option::unwrap() on a None value）

### ISSUE THREAD

**Issue by RRROS** [IsaacWoods/poplar#116]
[INFO ] kernel::syscall: [usb_bus_ehci]: PANIC: called `Option::unwrap()` on a `None` value (usb_bus_ehci/src/main.rs - 202:68)

**Comment by IsaacWoods** [comment]
Hey, thanks for trying Poplar out! This is unfortunately expected at this time due to not routing legacy PCI interrupts correctly (I'm using a modified QEMU to add MSIs to the EHCI device while I decide how I want to handle mixed legacy + MSI interrupts on PCI), but hopefully everything will work on an unmodified QEMU in the near future.

**Comment by IsaacWoods** [comment]
This should now be fixed as of 4e62fb0
